/** @type {import('next').NextConfig} */
module.exports = {
  env: {
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SCRAPINGDOG_API_KEY: process.env.SCRAPINGDOG_API_KEY,
    NEXT_PUBLIC_QUICKCHART_BASE_URL: process.env.NEXT_PUBLIC_QUICKCHART_BASE_URL,
    GUMROAD_CHECKOUT_URL: process.env.GUMROAD_CHECKOUT_URL
  }
};
